version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_CLIENTVAR: ${NEXT_PUBLIC_CLIENTVAR}
    working_dir: /app
    ports:
      - "3000:3000"
    image: omaha-playground-app
    volumes:
      - .:/app
      - /app/node_modules # To avoid conflicts with host node_modules
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_CLIENTVAR=${NEXT_PUBLIC_CLIENTVAR}
    command: ["node", "server.js"]
