version: "3.9"
services:
  app:
    platform: "linux/amd64"
    container_name: t3-app-container
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: ${NEXT_PUBLIC_CLIENTVAR}
    restart: always

    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - t3app
    volumes:
      - ./node_modules:/app/node_modules
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next
      - ./src:/app/src

  postgres:
    container_name: postgres-container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - t3app
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  t3app:

volumes:
  postgres_data:
