import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import { Header } from "../components/Header";

import { api, type RouterOutputs } from "../utils/api";

const Home: NextPage = (props) => {
  return (
    <>
      <Head>
        <title>Omaha Playground Collective</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

type Post = RouterOutputs["post"]["getAll"][0];

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const [selectedPost, setSelectedPost] = useState<Post | null>(null);

  const { data: posts, refetch: refetchPosts } = api.post.getAll.useQuery(
    undefined, // no input
    {
      enabled: sessionData?.user !== undefined,
      onSuccess: (data) => {
        setSelectedPost(selectedPost ?? data[0] ?? null);
      },
    },
  );

  const createPost = api.post.create.useMutation({
    onSuccess: () => {
      refetchPosts();
    },
  });

  return (
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div className="px-2">
        <ul className="menu rounded-box w-56 bg-base-100 p-2">
          {posts?.map((post) => (
            <li key={post.id}>
              <a
                href="#"
                onClick={(evt) => {
                  evt.preventDefault();
                  setSelectedPost(post);
                }}
              >
                {post.title}
              </a>
            </li>
          ))}
        </ul>
        <div className="divider"></div>
        <input
          type="text"
          placeholder="New Post"
          className="input input-bordered input-sm w-full"
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              createPost.mutate({
                title: e.currentTarget.value,
                content: "",
              });
              e.currentTarget.value = "";
            }
          }}
        />
      </div>
      <div className="col-span-3">
        <div>tags</div>
      </div>
    </div>
  );
};
