import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import { Header } from "~/components/header";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Omaha Playground Collective</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Content />
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: posts, refetch: refetchPosts } = api.post.getAll.useQuery(
    undefined,
    {
      enabled: !!sessionData?.user,
    },
  );

  const CreatePost = api.post.create.useMutation({});

  return (
    <div className="mx-5 mt-5 grid grid-cols-4 gap-2">
      <div className="px-2">
        <div className="divider"></div>
        <input 
          type="text"
          placeholder="New Post"
          className="input input-bordered input-sm w-full"
          onKeyDown={
            (e) => {
              if (e.key === "Enter") {
                CreatePost.mutate({
                  title: e.currentTarget.value,
                }, {
                  onSuccess: () => {
                    refetchPosts();
                  },
                });
                e.currentTarget.value = "";
              }
            }
          }
      </div>
      <div className="col-span-3"></div>
    </div>
  );
};
