import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { headers } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { Feature } from "./_components/Feature";
import Footer from "./_components/Footer";
import Header from "./_components/Header";
import Sidebar from "./_components/Sidebar";

import { Analytics } from "@vercel/analytics/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Omaha Playground Collective",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      data-theme="emerald"
      className="relative flex h-full w-full flex-col space-y-4"
    >
      <body className={`font-sans ${inter.variable}`}>
        <Header />
        <div className="grid w-full grid-cols-12">
          <section className="col-span-12 border-r border-gray-300 lg:col-span-8 lg:flex lg:flex-col">
            <Feature />
            <div className="divider flex w-full items-center justify-between px-10"></div>
            <div className="relative flex h-full w-full flex-col space-y-4">
              <TRPCReactProvider headers={headers()}>
                {children}
              </TRPCReactProvider>
            </div>
          </section>
          <Sidebar />
        </div>
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
